import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { db, type Party, formatMoney } from "./db";

export async function generateStatementPDF(party: Party, businessName: string, currencySymbol: string) {
  const txns = await db.transactions.where("partyId").equals(party.id!).sortBy("date");

  const doc = new jsPDF();
  const w = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(13, 148, 136);
  doc.rect(0, 0, w, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16); doc.setFont("helvetica", "bold");
  doc.text(businessName, 14, 13);
  doc.setFontSize(10); doc.setFont("helvetica", "normal");
  doc.text("Account Statement", 14, 21);

  // Party info
  doc.setTextColor(30);
  doc.setFontSize(12); doc.setFont("helvetica", "bold");
  doc.text(party.name, 14, 40);
  doc.setFontSize(9); doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  if (party.phone) doc.text(`Phone: ${party.phone}`, 14, 46);
  doc.text(`Type: ${party.type}`, 14, 52);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, w - 14, 46, { align: "right" });

  // Table
  let running = party.openingBalance || 0;
  const rows = [
    ["Opening", "—", "—", "—", formatMoney(running, currencySymbol)],
    ...txns.map(t => {
      running += t.type === "credit" ? t.amount : -t.amount;
      return [
        new Date(t.date).toLocaleDateString(),
        t.note || (t.type === "credit" ? "Received" : "Given"),
        t.type === "debit" ? formatMoney(t.amount, currencySymbol) : "—",
        t.type === "credit" ? formatMoney(t.amount, currencySymbol) : "—",
        formatMoney(running, currencySymbol),
      ];
    }),
  ];

  autoTable(doc, {
    startY: 60,
    head: [["Date", "Note", "Given", "Received", "Balance"]],
    body: rows,
    headStyles: { fillColor: [13, 148, 136], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [245, 250, 248] },
    margin: { left: 14, right: 14 },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  const label = running > 0 ? "Net: To receive" : running < 0 ? "Net: To pay" : "Settled";
  doc.text(`${label}  —  ${formatMoney(running, currencySymbol)}`, 14, finalY);

  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(140);
  doc.text("Generated by Hisaab Kitaab — offline Digital Khata for small business", 14, 287);

  return doc;
}

export async function downloadStatement(party: Party, businessName: string, symbol: string) {
  const doc = await generateStatementPDF(party, businessName, symbol);
  doc.save(`${party.name.replace(/\s+/g, "_")}_statement.pdf`);
}

export function shareWhatsApp(phone: string | undefined, text: string) {
  const cleaned = (phone || "").replace(/[^\d+]/g, "");
  const url = cleaned
    ? `https://wa.me/${cleaned.replace(/^\+/, "")}?text=${encodeURIComponent(text)}`
    : `https://wa.me/?text=${encodeURIComponent(text)}`;
  window.open(url, "_blank", "noopener");
}
